title = "Antropología Digital"
baseURL = "https://antropodigital.github.io/CirculodeEstudio/"
languageCode = "es"
theme = "ananke"
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Círculo de estudios de la UNSAM"
  facebook = "https://www.facebook.com/groups/ceantropodigital/"
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/Antropodigital/CirculodeEstudio"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
